name: chatty
services:
  postgres:
    image: postgres:17.3
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - docker.env
  pgadmin:
    image: dpage/pgadmin4:9.0
    volumes:
      - /data/pgadmin:/root/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - backend
    env_file:
      - docker.env
    depends_on:
      - postgres
  backend:
    build:
      context: .
      target: dev-deps
    command: pnpm dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - postgres
networks:
  backend:
    driver: bridge
