# Local compose file for development
name: chatty
services:
  postgres:
    image: postgres:17.3
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - private
    env_file:
      - docker.env
  backend:
    build:
      context: .
      target: dev-deps
    command: pnpm dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    networks:
      - private
    depends_on:
      - postgres
networks:
  private:
    driver: bridge
