name: chatty
services:
  postgres:
    image: postgres:17.3
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - docker.env
  pgadmin:
    image: dpage/pgadmin4:9.0
    ports:
      - "8080:80"
    networks:
      - backend
    env_file:
      - docker.env
    depends_on:
      - postgres
  backend:
    image: chatty-backend:1.0
    ports:
      - "3000:3000"
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - postgres
networks:
  backend:
    driver: bridge
